DROP TABLE STG_DCA_SALES;commit;
CREATE TABLE STG_DCA_SALES AS 
SELECT PROD_ID, CUST_ID,  TO_DATE('09/01/2018','MM/DD/YYYY') + ((TIME_ID - TO_DATE('12/31/2001','MM/DD/YYYY'))/((365*4)/153)) AS TIME_ID,CHANNEL_ID,QUANTITY_SOLD, AMOUNT_SOLD
FROM SH.SALES ;commit;

DROP TABLE STG_DCA_PRODUCTS ;commit;
CREATE TABLE STG_DCA_PRODUCTS AS SELECT * FROM SH.PRODUCTS;commit;
UPDATE STG_DCA_PRODUCTS SET PROD_SUBCATEGORY = 'Android Phones' WHERE PROD_SUBCATEGORY = 'Monitors';commit;
UPDATE STG_DCA_PRODUCTS SET PROD_SUBCATEGORY = 'Other Accessories' WHERE PROD_SUBCATEGORY = 'Accessories';commit;
UPDATE STG_DCA_PRODUCTS SET PROD_SUBCATEGORY = 'Jackets/Covers' WHERE PROD_SUBCATEGORY = 'Modems/Fax';commit;
UPDATE STG_DCA_PRODUCTS SET PROD_SUBCATEGORY = 'Bluetooth Devices' WHERE PROD_SUBCATEGORY = 'Memory';commit;
UPDATE STG_DCA_PRODUCTS SET PROD_SUBCATEGORY = 'Android Phones' WHERE PROD_SUBCATEGORY = 'CD-ROM';commit;
UPDATE STG_DCA_PRODUCTS SET PROD_SUBCATEGORY = 'iOS Phones' WHERE PROD_SUBCATEGORY = 'Printer Supplies';commit;
UPDATE STG_DCA_PRODUCTS SET PROD_CATEGORY = 'Mobile Phones' WHERE PROD_CATEGORY = 'Peripherals and Accessories';commit;
UPDATE STG_DCA_PRODUCTS SET PROD_CATEGORY = 'Computers' WHERE PROD_CATEGORY = 'Hardware';commit;
COMMIT;commit;

DROP TABLE DCA_SALES_DATA ;commit;
CREATE TABLE DCA_SALES_DATA AS 
(SELECT A.PROD_NAME AS PRODUCT, A.PROD_SUBCATEGORY AS SUB_CATEGORY, A.PROD_CATEGORY AS CATEGORY, B.CHANNEL_CLASS AS CHANNEL, C.CUST_ID, C.CUST_ID AS LOYALTY_ID, C.TIME_ID AS SALES_DATE, C.QUANTITY_SOLD AS QUANTITY,C.AMOUNT_SOLD AS VALUE 
FROM STG_DCA_PRODUCTS A, SH.CHANNELS B, STG_DCA_SALES C
WHERE A.PROD_ID = C.PROD_ID AND B.CHANNEL_ID = C.CHANNEL_ID 
AND CUST_ID IN (SELECT DISTINCT CUST_ID FROM SH.CUSTOMERS WHERE COUNTRY_ID=52790));commit;

DROP TABLE DCA_CUSTOMERS_DATA;commit;
CREATE TABLE DCA_CUSTOMERS_DATA AS 
(SELECT A.CUST_ID,A.CUST_FIRST_NAME AS FIRST_NAME,A.CUST_LAST_NAME AS LAST_NAME,A.CUST_GENDER AS GENDER,A.CUST_YEAR_OF_BIRTH AS AGE, A.CUST_MARITAL_STATUS AS MARITAL_STATUS, A.CUST_POSTAL_CODE AS ZIPCODE,A.CUST_CITY AS CITY,A.CUST_STATE_PROVINCE AS STATE, A.CUST_INCOME_LEVEL AS INCOME_LEVEL,A.CUST_CREDIT_LIMIT AS CREDIT_LIMIT
FROM STG_DCA_CUSTOMERS A 
WHERE A.CUST_ID IN (SELECT DISTINCT CUST_ID FROM DCA_SALES_DATA));commit;

DROP TABLE STG_DCA_CUSTOMERS;commit;
DROP TABLE STG_DCA_PRODUCTS;commit;
DROP TABLE STG_DCA_SALES;commit;
